package com.myspace.cursojbpmbasics.interfaz;

import java.util.Map;

import com.myspace.cursojbpmbasics.model.bo.Costos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public interface ISuma {

	/**
	 * Suma de dos valores
	 * @param mapa
	 * @return
	 */
	public Integer sumar (Map<?, ?> mapa);
	
	/**
	 * Sumar el valor y costo
	 * @param costos
	 * @return
	 */
	public Integer sumarCostos (Costos costos);
	
}
