package com.myspace.cursojbpmbasics.implementacion;

import java.util.Map;

import com.myspace.cursojbpmbasics.interfaz.ISuma;
import com.myspace.cursojbpmbasics.model.bo.Costos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Suma implements ISuma {


	@Override
	public Integer sumar(Map<?, ?> mapa) {
		int valor1 = (Integer) mapa.get("Valor1");
		int valor2 = (Integer) mapa.get("Valor2");
		
		int suma = valor1 +  valor2;
		System.out.println("SumarIn: " + suma);
		
		return suma;
	}

	@Override
	public Integer sumarCostos(Costos costos) {
		int valor1 = costos.getCosto();
		int valor2 = costos.getValor();
		
		int suma = valor1 +  valor2;
		System.out.println("SumarIn: " + suma);
		
		return suma;
	}
	
	
}