package com.myspace.cursojbpmintegrations.modelo.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DatosContacto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Dirección")
	private java.lang.String direccion;
	@org.kie.api.definition.type.Label(value = "Teléfono ")
	private java.lang.Integer telefono;

	public DatosContacto() {
	}

	public java.lang.String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(java.lang.String direccion) {
		this.direccion = direccion;
	}

	public java.lang.Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(java.lang.Integer telefono) {
		this.telefono = telefono;
	}

	public DatosContacto(java.lang.String direccion, java.lang.Integer telefono) {
		this.direccion = direccion;
		this.telefono = telefono;
	}

}