package com.myspace.cursojbpmbasics.model.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Costos")
public class Costos implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Costo")
	private java.lang.Integer costo;
	@org.kie.api.definition.type.Label(value = "Valor")
	private java.lang.Integer valor;

	public Costos() {
	}

	public java.lang.Integer getCosto() {
		return this.costo;
	}

	public void setCosto(java.lang.Integer costo) {
		this.costo = costo;
	}

	public java.lang.Integer getValor() {
		return this.valor;
	}

	public void setValor(java.lang.Integer valor) {
		this.valor = valor;
	}

	public Costos(java.lang.Integer costo, java.lang.Integer valor) {
		this.costo = costo;
		this.valor = valor;
	}

}