package com.myspace.cursojbpmbasics.model.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("DatosContacto")
public class DatosContacto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Teléfono  ")
	private java.lang.String telefono;
	@org.kie.api.definition.type.Label(value = "Celular")
	private java.lang.String celular;
	@org.kie.api.definition.type.Label(value = "Direción")
	private java.lang.String direccion;

	public DatosContacto() {
	}

	public java.lang.String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(java.lang.String telefono) {
		this.telefono = telefono;
	}

	public java.lang.String getCelular() {
		return this.celular;
	}

	public void setCelular(java.lang.String celular) {
		this.celular = celular;
	}

	public java.lang.String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(java.lang.String direccion) {
		this.direccion = direccion;
	}

	public DatosContacto(java.lang.String telefono, java.lang.String celular,
			java.lang.String direccion) {
		this.telefono = telefono;
		this.celular = celular;
		this.direccion = direccion;
	}

}